### ISSUE TITLE
Loading example plugin fails

### ISSUE THREAD

**Issue by eybisi** [jadx-decompiler/jadx-example-plugin#4]
Hi, after building jadx dev version I tried to load this example plugin which failed. It cant find `BasePluginOptionsBuilder` class. 
Jadx version: dev 

Logs:
```
Java.util.ServiceConfigurationError: jadx.api.plugins.JadxPlugin: Provider jadx.plugins.example.JadxExamplePlugin could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at jadx.plugins.tools.JadxExternalPluginsLoader.lambda$loadFromClsLoader$4(JadxExternalPluginsLoader.java:71)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1499)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at jadx.plugins.tools.JadxExternalPluginsLoader.loadFromClsLoader(JadxExternalPluginsLoader.java:71)
	at jadx.plugins.tools.JadxExternalPluginsLoader.loadFromJar(JadxExternalPluginsLoader.java:86)
	at jadx.plugins.tools.JadxExternalPluginsLoader.loadFromJar(JadxExternalPluginsLoader.java:56)
	at jadx.plugins.tools.JadxPluginsTools.fillMetadataFromJar(JadxPluginsTools.java:177)
	at jadx.plugins.tools.JadxPluginsTools.fillMetadata(JadxPluginsTools.java:172)
	at jadx.plugins.tools.JadxPluginsTools.resolveMetadata(JadxPluginsTools.java:55)
	at jadx.plugins.tools.JadxPluginsTools.install(JadxPluginsTools.java:47)
	at jadx.gui.settings.ui.plugins.PluginSettings.lambda$install$0(PluginSettings.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: jadx/api/plugins/options/impl/BasePluginOptionsBuilder
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at jadx-plugin:jadx-example-plugin-dev.jar//jadx.plugins.example.JadxExamplePlugin.<init>(JadxExamplePlugin.java:10)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 23 more
Caused by: java.lang.ClassNotFoundException: jadx.api.plugins.options.impl.BasePluginOptionsBuilder
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	```

**Comment by eybisi** [comment]
I used `./gradlew jar` command to build example plugin. Then tried to load via Plugins->Install Plugin : path  of the library `build/libs/jadx-example-plugin-dev.jar`
